load("@rules_python//python:defs.bzl", "py_binary", "py_library")

py_library(
    name = "release_tag_resolver_lib",
    srcs = ["release_tag_resolver.py"],
    visibility = ["//visibility:public"],
)

py_binary(
    name = "resolve_release_tag",
    srcs = ["release_tag_resolver.py"],
    main = "release_tag_resolver.py",
    visibility = ["//visibility:public"],
)
