name: "Bazel steward"
description: "Automatically searches bazel repositories for dependencies and updates them"
author: ""
inputs:
  configuration-path:
    description: "The path to bazel steward configuration"
    default: "./bazel-steward.yaml"
  github-token:
    description: "A token for the Github repository"
    default: ${{ github.token }}
  github-personal-token:
    description: "A personal token for triggering the workflows by closing and reopening pull requests"
    required: false
  use-release:
    description: "Whether to use prebuild jar from release, instead of compiling code"
    default: "true"
  push-to-remote:
    description: "Whether to push changes to remote and open pull requests"
    default: "true"
  additional-args:
    description: "Additional arguments to bazel steward jar"
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Download release
      if: ${{ inputs.use-release == 'true' }}
      run: |
        TAG_NAME=$(echo "${{ github.action_path }}" | grep -Po "(?<=\/)[^\/]*$")
        gh release download $TAG_NAME --pattern bazel-steward.jar --repo VirtusLab/bazel-steward
      env:
        GH_TOKEN: ${{ github.token }}
      shell: bash
    - name: Build jar file
      if: ${{ inputs.use-release != 'true' }}
      uses: ./.github
    - name: Setup git user
      uses: fregante/setup-git-user@v1
    - name: Run bazel steward
      run: |
        java -Dorg.slf4j.simpleLogger.defaultLogLevel=DEBUG -jar bazel-steward.jar \
        --github $PUSH_TO_REMOTE --config-path '${{ inputs.configuration-path }}' ${{ inputs.additional-args }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        PERSONAL_TOKEN: ${{ inputs.github-personal-token }}
        PUSH_TO_REMOTE: ${{ inputs.push-to-remote == 'true' && '--push-to-remote' || '' }}

branding:
  icon: 'umbrella'
  color: 'green'