name: "Bazel steward"
description: "Automatically searches bazel repositories for dependencies and updates them"
author: ""
inputs:
  configuration-path:
    description: "The path to bazel steward configuration"
    default: ".github/bazel-steward.yaml"
  github-token:
    description: "A token for the github repository"
    default: ${{ github.token }}
  base-branch:
    description: "Branch of the repository that will be scanned for dependencies"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build jar file
      uses: ./tools
    - name: Run bazel steward
      run: java -jar bazel-steward.jar --github --baseBranch ${{ inputs.base-branch }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}