name: "Bazel steward"
description: "Automatically searches bazel repositories for dependencies and updates them"
author: ""
inputs:
  configuration-path:
    description: "The path to bazel steward configuration"
    default: ".github/bazel-steward.yaml"
  github-token:
    description: "A token for the github repository"
    default: ${{ github.token }}
  use-release:
    description: "Weather to use prebuild jar from release, instead of compiling code"
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Where am I?
      run: |
        echo "github.action = ${{github.action}}"
        echo "github.action_path = ${{github.action_path}}"
        echo "github.action_ref = ${{github.action_ref}}"
        echo "github.action_repository = ${{github.action_repository}}"
        echo "github.action_status = ${{github.action_status}}"
        echo "github.actor = ${{github.actor}}"
        echo "github.api_url = ${{github.api_url}}"
        echo "github.base_ref = ${{github.base_ref}}"
        echo "github.env = ${{github.env}}"
        echo "github.event = ${{github.event}}"
        echo "github.event_name = ${{github.event_name}}"
        echo "github.event_path = ${{github.event_path}}"
        echo "github.graphql_url = ${{github.graphql_url}}"
        echo "github.head_ref = ${{github.head_ref}}"
        echo "github.job = ${{github.job}}"
        echo "github.ref = ${{github.ref}}"
        echo "github.ref_name = ${{github.ref_name}}"
        echo "github.ref_protected = ${{github.ref_protected}}"
        echo "github.ref_type = ${{github.ref_type}}"
        echo "github.path = ${{github.path}}"
        echo "github.repository = ${{github.repository}}"
        echo "github.repository_owner = ${{github.repository_owner}}"
        echo "github.repositoryUrl = ${{github.repositoryUrl}}"
        echo "github.retention_days = ${{github.retention_days}}"
        echo "github.run_id = ${{github.run_id}}"
        echo "github.run_number = ${{github.run_number}}"
        echo "github.run_attempt = ${{github.run_attempt}}"
        echo "github.server_url = ${{github.server_url}}"
        echo "github.sha = ${{github.sha}}"
        echo "github.token = ${{github.token}}"
        echo "github.workflow = ${{github.workflow}}"
        echo "github.workspace = ${{github.workspace}}"
      shell: bash
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Download release
      if: ${{ inputs.use-release == 'true' }}
      run: gh release download `echo ${{ github.action_path }} | grep -Po "(?<=\/)[^\/]*$"` --pattern bazel-steward.jar
      env:
        GH_TOKEN: ${{ github.token }}
      shell: bash
    - name: Build jar file
      if: ${{ inputs.use-release != 'true' }}
      uses: ./.github
    - uses: fregante/setup-git-user@v1
    - name: Run bazel steward
      run: java -jar bazel-steward.jar --github
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}

branding:
  icon: 'umbrella'
  color: 'green'