name: "Bazel steward"
description: "Automatically searches bazel repositories for dependencies and updates them"
author: ""
inputs:
  configuration-path:
    description: "The path to bazel steward configuration"
    default: ".github/bazel-steward.yaml"

runs:
  using: "composite"
  steps:
      - uses: ./gh-action
      - run: java -jar bazel-steward.jar
        shell: bash