name: "Bazel steward"
description: "Automatically searches bazel repositories for dependencies and updates them"
author: ""
inputs:
  configuration-path:
    description: "The path to bazel steward configuration"
    default: ".github/bazel-steward.yaml"
  github-token:
    description: "A token for the github repository"
    required: true

runs:
  using: "composite"
  steps:
      - uses: ./tools
      - run: java -jar bazel-steward.jar --github
        shell: bash