# This entry allows using custom themes that are hosed on Github.
remote_theme: just-the-docs/just-the-docs

# Uncomment this entry for local development
# theme: just-the-docs

color_scheme: light_green

logo: "/images/logo.png"

aux_links:
  "Bazel Steward on GitHub":
    - "https://github.com/VirtusLab/bazel-steward"
    
nav_external_links:
  - title: Bazel Steward on GitHub
    url: "https://github.com/VirtusLab/bazel-steward"


callouts:
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red