name: Dependencies

on:
  schedule:
    - cron: '0 15 * * *'
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  bazel-steward:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: VirtusLab/bazel-steward@v0.1.0