name: Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Reopen
        run: |
          gh pr close 128
          gh pr reopen 128
